import type { Itinerario, Parada } from '../tipos';

// Itinerario del viaje. Todas las horas son hora de China.
// Si un plan acaba pasada la medianoche se escribe como "25:30" (01:30 del día siguiente).

/**
 * Coordenadas WGS-84 [lat, lng] de cada sitio (OpenStreetMap). Aproximadas, a falta de
 * confirmar el número exacto: tramo este de Nanjing Road, Songmont (huaihai), Hush, Dongxin, CUBIC3 e
 * Hinichijou.
 */
const C = {
  pvg: [31.151124, 121.798652],
  hotel: [31.2500138, 121.4467433],
  museoHistoriaNatural: [31.2368655, 121.4577002],
  huanghe: [31.2366304, 121.4660009],
  nanjingOeste: [31.2370467, 121.4702684],
  nanjingEste: [31.2386, 121.4785],
  joyCity: [31.2457033, 121.4675727],
  noria: [31.2461038, 121.4675959],
  disney: [31.1462523, 121.6562825],
  estacionShanghai: [31.2504165, 121.4505223],
  estacionNankin: [32.0890655, 118.7913961],
  comidaJiming: [32.0597786, 118.7914078],
  museo: [32.0616702, 118.7901099],
  jiming: [32.0629615, 118.7899275],
  txHuaihai: [31.2225113, 121.4642123],
  lyceum: [31.2235781, 121.4554307],
  huaihai: [31.2188995, 121.4552697],
  yuyuan: [31.2273348, 121.4912311],
  nanxiang: [31.2285341, 121.4871017],
  // Paseo del Bund junto a la plaza de Chen Yi (antes había una coordenada desplazada, en el río).
  bund: [31.24103, 121.4866],
  speakLow: [31.2170628, 121.4605836],
  hush: [31.2205, 121.465],
  wukang: [31.2062561, 121.4337292],
  dongxin: [31.2079627, 121.4345823],
  demarzo: [31.2151229, 121.4355285],
  cubic3: [31.2129028, 121.4538854],
  hinichijou: [31.2129028, 121.4538854],
  lujiazui: [31.23962, 121.4960369],
  perla: [31.2419464, 121.4952604],
  // Subparadas (OpenStreetMap). Miniso Land, a falta de confirmar el número exacto.
  jiaJia: [31.236418, 121.4663129],
  primerBaihuo: [31.2370344, 121.4702701],
  primerAlimentacion: [31.2375414, 121.47216],
  shimao: [31.2363682, 121.471206],
  minisoLand: [31.2379593, 121.4766991],
  hongyi: [31.238756, 121.4800058],
  bailianZX: [31.239143, 121.4787764],
  daimaru: [31.240375, 121.4810468],
  disneytown: [31.1423191, 121.6569261],
  // Sitios recomendados del día 1 (OpenStreetMap). Shanxi South Road: punto medio del tramo.
  // Puente Baihe: punto medio de la pasarela curva de ~250 m (OSM way 1346332993).
  baihe: [31.24835, 121.44524],
  m50: [31.24988, 121.44474],
  qianShu: [31.25087, 121.44089],
  yufo: [31.24359, 121.43985],
  parkHotel: [31.2356, 121.46699],
  taiShengYuan: [31.23599, 121.46656],
  granCine: [31.23485, 121.46653],
  museoHistoria: [31.23262, 121.46662],
  jwMarriott: [31.23233, 121.46523],
  shenDaCheng: [31.23764, 121.47385],
  wingOn: [31.23681, 121.47378],
  muEn: [31.2352, 121.47134],
  shanxiNan: [31.2393, 121.4776],
  laoDaFang: [31.237865, 121.475643],
  huawei: [31.23951, 121.480705],
  heping: [31.2411331, 121.4846079],
  waibaidu: [31.245307, 121.485744],
  zhapu: [31.246148, 121.483294],
  yuanmingyuan: [31.243156, 121.483836],
  sihang: [31.24226, 121.46693],
  fotografiska: [31.24166, 121.46527],
  zhejiangQiao: [31.24334, 121.47202],
  suheMixc: [31.24437, 121.47387],
  // Noche del día 2, junto al hotel.
  lawson: [31.25015, 121.44684],
  mcdonaldsChangshou: [31.24144, 121.4324],
} satisfies Record<string, [number, number]>;

/** Shanghai Disneyland (OpenStreetMap). Los espectáculos van en su mejor punto para verlos. */
const D = {
  tron: [31.144241, 121.651788],
  sieteEnanitos: [31.147637, 121.655494],
  castillo: [31.145739, 121.655327],
  zootopia: [31.148863, 121.655259],
  desfile: [31.144833, 121.656338],
  piratas: [31.148227, 121.658182],
  rapidos: [31.144942, 121.659261],
  soaring: [31.145584, 121.661181],
  illuminate: [31.144218, 121.65702],
  peterPan: [31.145422, 121.6536],
  corazon: [31.14546, 121.655634],
  teatro: [31.143218, 121.656733],
  tormenta: [31.147702, 121.659506],
  rex: [31.145737, 121.652307],
  jetPacks: [31.143759, 121.654395],
  cuerdas: [31.145796, 121.659538],
  zootopiaCentro: [31.14857, 121.655428],
  linaBell: [31.145457, 121.659609],
  duffy: [31.144767, 121.657684],
  marvel: [31.144673, 121.654353],
  pixar: [31.142657, 121.652407],
  alicia: [31.146752, 121.65528],
  doceAmigos: [31.145158, 121.656745],
  tortuga: [31.146797, 121.659259],
  jumbeaux: [31.148372, 121.65503],
  cookieAnn: [31.144091, 121.657299],
  lunaErrante: [31.145798, 121.657258],
  avenidaM: [31.143503, 121.657315],
  estrellaDeseos: [31.140777, 121.6627],
  // Halloween (días «Spook-tacular»): coordenadas oficiales convertidas a WGS-84 u OSM.
  fiestaTomorrowland: [31.14423, 121.653023],
  fiestaTesoro: [31.147112, 121.658622],
  bosqueFestival: [31.147177, 121.654316],
  evergreen: [31.146867, 121.65252],
  meetingPost: [31.145849, 121.652628],
  stargazer: [31.143343, 121.653849],
  timothy: [31.144417, 121.655589],
} satisfies Record<string, [number, number]>;

const en = ([lat, lng]: [number, number]) => ({ lat, lng });

const HOTEL = {
  nombre: 'Hotel Aqua Suhe NO.1',
  local: '上海静安苏河1號酒店',
  categoria: 'hotel',
  ...en(C.hotel),
  direccion: '688 Hengfeng Road, Jing’an',
  direccionLocal: '上海市静安区恒丰路688号',
} satisfies Omit<Parada, 'hora'>;

const PVG = {
  nombre: 'Aeropuerto de Pudong (PVG), T1',
  local: '浦东国际机场1号航站楼',
  categoria: 'transporte',
  ...en(C.pvg),
} satisfies Omit<Parada, 'hora'>;

const enlace = (texto: string, url: string) => ({ texto, url });

export const itinerario: Itinerario = {
  titulo: 'Shanghái y Nankín',
  subtitulo: '21–26 de octubre de 2026 · 2 personas',
  // Cambio aproximado de julio de 2026; solo sirve para dar una idea en euros.
  yuanesPorEuro: 7.7,
  dias: [
    {
      fecha: '2026-10-21',
      titulo: 'Llegada, siesta, Nanjing Road y noria',
      ciudad: 'Shanghái',
      notas:
        'Plan: dormir hasta ~14:30 y salir a las 15:00. Comida tardía, tiendas por Nanjing Road, el Bund al encenderse las luces y la noria de noche.\n' +
        'Entre las 14:00 y las 17:00 muchos restaurantes tradicionales cierran: por eso la comida es en Huanghe Road, que sirve toda la tarde.',
      paradas: [
        {
          ...PVG,
          hora: '07:00',
          fin: '08:50',
          notas:
            'Llegada desde París. Air France y KLM operan en la Terminal 1 (confirmarlo en la tarjeta de embarque).\n' +
            'Inmigración, equipaje y traslado al hotel.',
        },
        {
          ...HOTEL,
          hora: '10:00',
          fin: '15:00',
          llegada: {
            modo: 'taxi',
            detalle: 'Taxi o DiDi: ~50 km; 40–45 min sin tráfico, 60–75 min en hora punta. Unos 200 ¥',
            min: 70,
          },
          notas:
            'El hotel nos dejará entrar antes si hay habitaciones disponibles; si no, intentarán resolverlo lo antes posible. Plan: dormir hasta ~14:30.\n' +
            'Si hay que esperar: dejar las maletas en consigna y dar un paseo corto por Suzhou Creek, justo detrás del hotel: por el puente Baihe (abierto en 2025) se llega a M50 en unos 550 m.',
          reserva: '5 noches, del 21 al 26. Salida antes de las 12:00.',
          subparadas: [
            {
              nombre: 'Puente Baihe (Lily Bridge)',
              local: '苏州河百合桥',
              opcional: true,
              ...en(C.baihe),
              direccionLocal: '恒丰路苏州河百合桥（近莫干山路50号M50）',
              notas: 'Pasarela colgante sobre el Suzhou, abierta en 2025, con forma de pétalos de azucena: paseo corto y atajo a M50. Gratis.',
            },
            {
              nombre: 'M50, barrio de arte',
              local: 'M50创意园',
              opcional: true,
              ...en(C.m50),
              direccionLocal: '上海市普陀区莫干山路50号',
              notas: 'Fábricas textiles convertidas en galerías (ShanghART, Island6), murales y cafés con terraza. Galerías de ~10:00 a 18:00; casi todas gratis.',
            },
            {
              nombre: '1000 Trees',
              local: '天安千树',
              opcional: true,
              ...en(C.qianShu),
              direccionLocal: '上海市普陀区莫干山路600号',
              notas: 'El «bosque colgante» de Heatherwick, la foto más compartida de la zona en Xiaohongshu. Mejor de día; la mejor vista, desde el puente de Changhua Road.',
            },
            {
              nombre: 'Templo del Buda de Jade',
              local: '玉佛禅寺',
              opcional: true,
              ...en(C.yufo),
              direccionLocal: '上海市普陀区安远路170号',
              notas: 'Templo budista en activo con dos budas de jade birmano (al sentado no se le pueden hacer fotos). 8:00–16:30, unos 20 ¥. A 1,3 km: mejor en taxi.',
            },
          ],
          enlaces: [enlace('Ficha del hotel', 'https://sg.trip.com/hotels/jing-an-district-hotel-detail-2895314/aqua-suhe-no-1-hotel-shanghai-jingan/')],
        },
        {
          hora: '15:15',
          fin: '16:00',
          nombre: 'Comida en Huanghe Road: Yang’s Dumpling',
          corto: 'Yang’s Dumpling',
          local: '小杨生煎（黄河路）',
          categoria: 'comida',
          ...en(C.huanghe),
          llegada: { modo: 'taxi', min: 15 },
          direccion: '97 Huanghe Road, junto a People’s Square',
          direccionLocal: '黄河路97号',
          notas:
            'Shengjian (bollos fritos de sopa), distintos de los xiaolongbao del jueves: un plato de 4 cuesta unos 12 ¥. Abre hasta tarde.\n' +
            'Huanghe Road se puso de moda por la serie «Blossoms Shanghai» (繁花).',
          gastos: [{ concepto: 'comida', min: 25, max: 45 }],
          subparadas: [
            {
              nombre: 'Jia Jia Tang Bao',
              local: '佳家汤包',
              opcional: true,
              ...en(C.jiaJia),
              direccionLocal: '黄河路90号',
              notas: 'En la misma calle: de los xiaolongbao más famosos de Shanghái (unos 40 ¥ por persona). Abre de 07:30 a 20:00.',
            },
            {
              nombre: 'Park Hotel: vestíbulo y pastelería',
              local: '国际饭店',
              opcional: true,
              ...en(C.parkHotel),
              direccionLocal: '上海市黄浦区黄河路28号',
              notas: 'Rascacielos art déco de Hudec (1934), con la marca del «kilómetro cero» de Shanghái en el vestíbulo. Su 蝴蝶酥 (~30 ¥ la bolsa) tiene colas de 1 a 4 h: mirar, no hacer cola.',
            },
            {
              nombre: 'Tai Sheng Yuan, el restaurante de «Blossoms»',
              local: '苔圣园酒家',
              opcional: true,
              ...en(C.taiShengYuan),
              direccionLocal: '黄河路50号',
              notas: 'El restaurante de 1993 que inspiró el 至真园 de la serie 繁花. A esa hora está cerrado (abre a las 16:30): foto de la fachada.',
            },
            {
              nombre: 'Grand Cinema',
              local: '大光明电影院',
              opcional: true,
              ...en(C.granCine),
              direccionLocal: '上海市黄浦区南京西路216号',
              notas: 'Cine art déco de Hudec (1933), todavía en activo: el vestíbulo, con su firma en latón en el suelo, y la escalera se ven en 10 minutos.',
            },
            {
              nombre: 'Museo de Historia de Shanghái',
              local: '上海市历史博物馆',
              opcional: true,
              ...en(C.museoHistoria),
              direccionLocal: '上海市黄浦区南京西路325号',
              notas: 'En el antiguo hipódromo, con su torre del reloj; cuenta muy bien la historia de la ciudad. Gratis y sin reserva, pero la última entrada es a las 16:00: solo si se termina de comer pronto.',
            },
            {
              nombre: 'Vistas desde la planta 38 del JW Marriott',
              local: '上海明天广场JW万豪酒店',
              opcional: true,
              ...en(C.jwMarriott),
              direccionLocal: '上海市黄浦区南京西路399号',
              notas: 'El vestíbulo del hotel está en la planta 38: se sube en ascensor y se ve People’s Square con Pudong al fondo. Gratis; tomar algo es opcional.',
            },
          ],
          enlaces: [enlace('Huanghe Road', 'https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240110/1ba02195e1ef4de49fabee498555c64d.html')],
        },
        {
          hora: '16:05',
          fin: '17:05',
          nombre: 'Nanjing Road: tramo de People’s Square',
          corto: 'People’s Square',
          local: '南京路步行街 · 第一百货',
          categoria: 'compras',
          ...en(C.nanjingOeste),
          llegada: { modo: 'a_pie' },
          notas:
            'Inicio de la calle peatonal.\n' +
            'Para compras grandes, preguntar en atención al cliente por la devolución de impuestos para turistas (con el pasaporte; se cobra en el aeropuerto).',
          subparadas: [
            {
              nombre: 'No. 1 Department Store',
              local: '上海市第一百货商店',
              ...en(C.primerBaihuo),
              notas: 'Grandes almacenes históricos, con zona de anime y figuras.',
            },
            {
              nombre: 'First Food Store',
              local: '第一食品商店',
              ...en(C.primerAlimentacion),
              direccionLocal: '南京东路720号',
              notas: 'Snacks y dulces de todo el país.',
            },
            {
              nombre: 'Shimao Plaza: LEGO, M&M’s y Pop Mart',
              local: '上海世茂广场',
              opcional: true,
              ...en(C.shimao),
              notas: 'Tiendas insignia de LEGO y M&M’s y, desde diciembre de 2025, una de Pop Mart de 800 m².',
            },
            {
              nombre: 'Shen Da Cheng',
              local: '沈大成',
              opcional: true,
              ...en(C.shenDaCheng),
              direccionLocal: '上海市黄浦区南京东路636号',
              notas: 'Dulces de arroz glutinoso desde 1875, con cola de gente de aquí: 条头糕 o 双酿团, a 4–8 ¥ la pieza (las ventanillas 10 y 11 venden sueltas). 7:30–20:30.',
            },
            {
              nombre: 'Wing On, grandes almacenes de 1918',
              local: '永安百货',
              opcional: true,
              ...en(C.wingOn),
              direccionLocal: '上海市黄浦区南京东路635号',
              notas: 'Edificio protegido que sale en 繁花, unido por pasarelas a la torre Wing On de 1933. Enfrente de Shen Da Cheng: basta con la fachada.',
            },
            {
              nombre: 'Iglesia de Mu’en',
              local: '沐恩堂',
              opcional: true,
              ...en(C.muEn),
              direccionLocal: '上海市黄浦区西藏中路316号',
              notas: 'Iglesia gótica de ladrillo rojo reformada por Hudec en 1931: con el Park Hotel y el Grand Cinema, el trío de Hudec. Entre semana, solo por fuera.',
            },
          ],
          enlaces: [
            enlace('Guía de tiendas de Nanjing Road', 'https://www.wanderinchina.com/es/destinations/shanghai/nanjing-east-road/shopping/'),
          ],
        },
        {
          hora: '17:20',
          fin: '18:10',
          nombre: 'Nanjing Road: tramo hacia el Bund',
          local: '南京东路步行街',
          categoria: 'compras',
          ...en(C.nanjingEste),
          llegada: { modo: 'a_pie' },
          notas:
            'Marcas chinas y cosas curiosas. Por la tarde-noche se encienden los neones de la calle. Posición en el mapa aproximada.',
          subparadas: [
            {
              nombre: 'Miniso Land',
              local: '名创优品 MINISO LAND',
              ...en(C.minisoLand),
              direccionLocal: '上海市黄浦区南京东路步行街 名创优品全球壹号店',
              notas: 'La tienda Miniso que más vende del mundo: tres plantas de licencias (Disney, Sanrio, Harry Potter, anime) y un pasillo de cajas sorpresa.',
            },
            {
              nombre: 'Pop Mart Global Flagship',
              local: '泡泡玛特 · 宏伊国际广场',
              ...en(C.hongyi),
              notas: 'En Hongyi Plaza: figuras sorpresa de edición Shanghái.',
            },
            {
              nombre: 'Bailian ZX',
              local: '百联ZX',
              opcional: true,
              ...en(C.bailianZX),
              notas: 'Seis plantas de anime y videojuegos.',
            },
            {
              nombre: 'NEW ONE (antes New World Daimaru)',
              local: '新世界新丸中心',
              opcional: true,
              ...en(C.daimaru),
              notas: 'Famoso por sus escaleras mecánicas doradas en espiral. Desde 2026 se llama NEW ONE y se reforma sin cerrar: puede haber zonas en obras.',
            },
            {
              nombre: 'Calle de los laozihao (Shanxi South Road)',
              local: '春启新巷 · 山西南路老字号美食街',
              opcional: true,
              ...en(C.shanxiNan),
              direccionLocal: '上海市黄浦区山西南路（南京东路至天津路段）',
              notas: 'Desde febrero de 2026 están aquí, de forma provisional, las casas de siempre de Yunnan Road: shengjian de 大壶春, pollo blanco y congee de 小绍兴, café de 德大 (1897).',
            },
            {
              nombre: 'Zhen Lao Da Fang',
              local: '真老大房',
              opcional: true,
              ...en(C.laoDaFang),
              direccionLocal: '上海市黄浦区南京东路536号',
              notas: 'La cola más famosa de Nanjing Road: 鲜肉月饼, hojaldre relleno de cerdo recién horneado, para comer caliente (5–10 ¥). Pasado el Medio Otoño hay menos cola.',
            },
            {
              nombre: 'Huawei Flagship',
              local: '华为旗舰店',
              opcional: true,
              ...en(C.huawei),
              direccionLocal: '上海市黄浦区南京东路233号',
              notas: 'La que fue la mayor tienda Huawei del mundo: plegables, HarmonyOS y coches 问界 que no se ven en España. 10:00–22:00, gratis.',
            },
          ],
        },
        {
          hora: '18:30',
          fin: '19:05',
          nombre: 'The Bund al encenderse las luces',
          corto: 'el Bund',
          local: '外滩',
          categoria: 'mirador',
          ...en(C.bund),
          llegada: { modo: 'a_pie' },
          notas:
            'Primera vista de Lujiazui iluminado: en octubre las luces del Bund y de Lujiazui suelen estar encendidas de 18:00 a 22:00 (anochece hacia las 17:25). A las 19:00 suenan las campanadas del reloj de la Aduana.\n' +
            'El ferry de 2 ¥ que cruza desde Jinling East Road deja de salir hacia las 18:30.',
          subparadas: [
            {
              nombre: 'Peace Hotel: vestíbulo y Jazz Bar',
              local: '和平饭店',
              opcional: true,
              ...en(C.heping),
              direccionLocal: '上海市黄浦区南京东路20号',
              notas: 'Hotel de Sassoon (1929): la cúpula octogonal del vestíbulo es la foto clásica. La Old Jazz Band toca desde ~19:00 (una bebida obligatoria, 100–300 ¥ + 15 %). Está en obras: será Raffles en 2027.',
            },
            {
              nombre: 'Garden Bridge (Waibaidu)',
              local: '外白渡桥',
              opcional: true,
              ...en(C.waibaidu),
              direccionLocal: '上海市黄浦区中山东一路外白渡桥',
              notas: 'Puente de acero de 1907, iluminado, con Broadway Mansions detrás: el mejor sitio para fotos con gente. A unos 10 minutos por el paseo.',
            },
            {
              nombre: 'Puente de Zhapu Road',
              local: '乍浦路桥',
              opcional: true,
              ...en(C.zhapu),
              direccionLocal: '上海市黄浦区南苏州路虎丘路口 乍浦路桥',
              notas: 'El mirador de los fotógrafos chinos: desde el centro, mirando al este, salen juntos Broadway Mansions, el Garden Bridge y las tres torres de Lujiazui, con reflejos en el río.',
            },
            {
              nombre: 'Yuanmingyuan Road (Bund Origin)',
              local: '圆明园路 · 外滩源',
              opcional: true,
              ...en(C.yuanmingyuan),
              direccionLocal: '上海市黄浦区圆明园路（北京东路口）',
              notas: 'Calle peatonal y tranquila de edificios de ladrillo de los años 20 y 30, con luz cálida por la noche: para volver por detrás del Bund.',
            },
          ],
        },
        {
          hora: '19:20',
          fin: '20:20',
          nombre: 'Jing’an Joy City: maleta y ropa',
          local: '静安大悦城',
          categoria: 'compras',
          ...en(C.joyCity),
          llegada: { modo: 'taxi', detalle: 'Taxi desde el Bund (~3 km)', min: 15 },
          direccionLocal: '上海市静安区西藏北路166号',
          notas:
            'Maleta: las de 90分 (NINETYGO) y Mijia son la opción china con mejor calidad/precio (policarbonato, ruedas silenciosas, candado TSA). Precios orientativos: 20″ ~200–500 ¥, 24″ ~300–700 ¥, 28″ ~460 ¥ en adelante.\n' +
            'Para comparar o si no hay existencias: en JD o Taobao son algo más baratas y llegan al hotel en 1–2 días. En los grandes almacenes de Nanjing Road predominan marcas internacionales más caras.\n' +
            'Antes de elegir el tamaño, revisar la franquicia de equipaje de los cuatro vuelos, sobre todo el Barcelona–Málaga de Vueling (según la tarifa, podría hacer falta añadir la maleta).\n' +
            'Ropa imprescindible para Disneyland. Las tiendas cierran a las 22:00.\n' +
            'Las luces del río Suzhou se apagan hacia las 21:30 entre semana (estimado): mejor ver la orilla antes.',
          subparadas: [
            {
              nombre: 'Tienda Xiaomi',
              local: '小米之家',
              notas: 'Maletas 90分 (NINETYGO) y Mijia. En el edificio sur, planta baja, según información de hace unos años: confirmarlo.',
            },
            {
              nombre: 'Sihang Warehouse',
              local: '四行仓库',
              opcional: true,
              ...en(C.sihang),
              direccionLocal: '上海市静安区光复路21号',
              notas: 'Escenario de la defensa de 1937 (la película «The Eight Hundred»): de noche, el muro oeste con los impactos desde la plaza, y el río desde el puente de Xizang Road. El museo cierra a las 16:30.',
            },
            {
              nombre: 'Fotografiska Shanghai',
              local: 'Fotografiska影像艺术中心',
              opcional: true,
              ...en(C.fotografiska),
              direccionLocal: '上海市静安区光复路127号',
              notas: 'Museo sueco de fotografía en un almacén junto al río, con bar dentro: de lo poco cultural abierto de noche (10:30–23:00, última entrada hacia las 22:00; 80 ¥).',
            },
            {
              nombre: 'Puente de Zhejiang Road',
              local: '浙江路桥',
              opcional: true,
              ...en(C.zhejiangQiao),
              direccionLocal: '上海市静安区浙江北路北苏州路口 浙江路桥',
              notas: 'Puente de celosía de acero de 1906, uno de los dos centenarios del centro (el otro es el Garden Bridge). Muy fotogénico, y de camino a Suhe MixC.',
            },
            {
              nombre: 'Suhe MixC World y Shenyu Li',
              local: '苏河湾万象天地 · 慎余里',
              opcional: true,
              ...en(C.suheMixc),
              direccionLocal: '上海市静安区福建北路100号',
              notas: 'Centro comercial «cañón» bajo un parque, muy de gente de aquí: arriba, el templo de Mazu de 1884 reconstruido; al lado, el lane shikumen Shenyu Li (1931), con bares y cenas tardías.',
            },
          ],
          enlaces: [
            enlace('Joy City', 'https://english.shanghai.gov.cn/en-ShoppingCenters/20231217/dbb23c40ef1b4ff68794226b8ca37d1a.html'),
            enlace('Equipaje en Vueling', 'https://help.vueling.com/hc/es/articles/19798835176081-Equipaje-de-mano-Maletas-de-mano'),
          ],
        },
        {
          hora: '20:25',
          fin: '21:00',
          nombre: 'Noria Sky Ring',
          corto: 'la noria',
          local: 'SKY RING摩天轮',
          categoria: 'mirador',
          ...en(C.noria),
          llegada: { modo: 'a_pie' },
          notas:
            'En la azotea del edificio norte, con acceso por la planta 8. Las cabinas tienen luz regulable y altavoz Bluetooth.\n' +
            'Trip.com da como horario 11:00–21:00 con última entrada a las 21:00 (una guía oficial antigua decía hasta las 22:00): confirmarlo ese día. Si abre hasta las 22:00, subir más tarde y cenar antes.\n' +
            'Algunas reseñas avisan de que desde arriba se ve sobre todo la ciudad cercana; los rascacielos de Lujiazui quedan lejos.',
          gastos: [{ concepto: 'entrada (desde)', min: 60 }],
        },
        {
          hora: '21:00',
          fin: '21:50',
          nombre: 'Cena en Top Banana Market',
          corto: 'la cena',
          categoria: 'comida',
          ...en(C.noria),
          llegada: { modo: 'a_pie' },
          notas:
            'Mercado gastronómico de cocinas asiáticas con mesas compartidas (abrió en 2026), con bebidas y postres.\n' +
            'Está en la planta baja del edificio norte de Joy City. Confirmar a qué hora cierra; si cierra pronto, cenar antes de subir a la noria.',
          gastos: [{ concepto: 'cena (estimado, sin precios publicados)', min: 60, max: 120 }],
          subparadas: [
            { nombre: 'Opalm Asia', notas: 'Cocina del sudeste asiático.' },
            { nombre: 'Nuu Nuu', notas: 'Tempura.' },
            { nombre: 'Karasuma', notas: 'Sukiyaki de wagyu para comer en barra.' },
            { nombre: 'Wen Made', notas: 'Fideos salteados.' },
          ],
          enlaces: [enlace('Top Banana Market', 'https://english.shanghai.gov.cn/en-FirstStores/20260211/4976961a80794cf495e4eb67df6371ee.html')],
        },
        {
          ...HOTEL,
          hora: '22:05',
          llegada: { modo: 'taxi', min: 10 },
        },
      ],
    },
    {
      fecha: '2026-10-22',
      titulo: 'Moda china, casco antiguo y noche de salida',
      ciudad: 'Shanghái',
      notas: 'Levantarnos a las 10:00.',
      paradas: [
        {
          hora: '10:30',
          fin: '12:45',
          nombre: 'Middle Huaihai Road: TX Huaihai',
          corto: 'TX Huaihai',
          local: 'TX淮海｜年轻力中心',
          categoria: 'compras',
          ...en(C.txHuaihai),
          llegada: { modo: 'metro', detalle: 'Línea 1 hasta South Huangpi Road', min: 20 },
          direccionLocal: '淮海中路523号',
          notas:
            'Prioridad a marcas locales, y otras tiendas que nos gusten al recorrer la calle.\n' +
            'TX Huaihai abre de 11:00 a 22:00.',
          subparadas: [
            {
              nombre: 'Pane',
              notas: 'En TX Huaihai, planta baja (L1-05/06). En festivos ha tenido colas de más de 40 min.',
            },
            {
              nombre: 'Mason Prince',
              direccionLocal: '淮海中路528号',
              notas: 'Enfrente de TX Huaihai.',
            },
          ],
          enlaces: [
            enlace('Guía de tiendas de Huaihai', 'https://english.shanghai.gov.cn/en-TrendyStores/20260525/8fc944e699224a4e9e9a609ad33fa0c0.html'),
          ],
        },
        {
          hora: '13:00',
          fin: '14:00',
          nombre: 'Lanxin (Lyceum Restaurant)',
          local: '兰心餐厅',
          categoria: 'comida',
          ...en(C.lyceum),
          llegada: { modo: 'a_pie' },
          direccion: '130 Jinxian Road',
          direccionLocal: '进贤路130号',
          notas:
            'Cocina shanghainesa. No admite reservas. Horario: 11:00–13:30 y 17:00–21:00: al mediodía cierra a las 13:30, así que conviene no llegar más tarde de las 13:00.\n' +
            'Alternativa si preferimos pato pekinés: Quanjude (no imprescindible).',
          gastos: [{ concepto: 'comida (gasto medio por persona en las reseñas: 60–80 ¥)', min: 60, max: 90 }],
        },
        {
          hora: '14:10',
          fin: '15:00',
          nombre: 'Más tiendas por Huaihai',
          local: '淮海中路',
          categoria: 'compras',
          ...en(C.huaihai),
          llegada: { modo: 'a_pie' },
          notas:
            'Songmont para mirar bolsos, no como compra obligatoria porque sube de presupuesto (su tienda en esta calle está sin confirmar).',
        },
        {
          ...HOTEL,
          hora: '15:30',
          fin: '16:15',
          llegada: { modo: 'metro', detalle: 'Línea 1 o taxi', min: 25 },
          notas: 'Dejar las compras y descansar.',
        },
        {
          hora: '16:45',
          fin: '18:25',
          nombre: 'Yuyuan y Shanghai Old Street',
          corto: 'Yuyuan',
          local: '上海老街',
          categoria: 'barrio',
          ...en(C.yuyuan),
          llegada: { modo: 'taxi', min: 25 },
          notas:
            'Arquitectura, ambiente y tiendas.\n' +
            'El jardín interior de Yuyuan no está incluido: cierra pronto y chocaría con las compras.',
          subparadas: [
            {
              nombre: 'Semir, tienda insignia',
              local: '森马',
              notas: 'Marca china de ropa diaria, con artículos exclusivos de Shanghái.',
            },
          ],
          enlaces: [
            enlace('Semir en Yuyuan', 'https://english.shanghai.gov.cn/en-Latest-WhatsNew/20260917/1213b27578094564b1ad9630d36c24f2.html'),
          ],
        },
        {
          hora: '18:30',
          fin: '19:30',
          nombre: 'Xiaolongbao en Nanxiang',
          local: '南翔馒头店',
          categoria: 'comida',
          ...en(C.nanxiang),
          llegada: { modo: 'a_pie' },
          notas:
            'Cena, en el bazar de Yuyuan. Ajustar según la cola y el horario efectivo.\n' +
            'Cada planta tiene un precio: en la planta baja, para llevar, 6 xiaolongbao cuestan 30 ¥; en la primera planta, 38 ¥ (o 48 ¥ los de cangrejo); en la segunda, con vistas, menús de 80–100 ¥.',
          gastos: [{ concepto: 'cena (según la planta)', min: 40, max: 100 }],
        },
        {
          hora: '20:00',
          fin: '21:30',
          nombre: 'The Bund',
          local: '外滩',
          categoria: 'mirador',
          ...en(C.bund),
          llegada: { modo: 'a_pie' },
          notas: 'Paseo y vistas nocturnas de Lujiazui.',
        },
        {
          hora: '22:00',
          fin: '23:30',
          nombre: 'Speak Low',
          local: 'Speak Low',
          categoria: 'ocio',
          ...en(C.speakLow),
          llegada: { modo: 'taxi', min: 20 },
          direccion: '579 Middle Fuxing Road',
          direccionLocal: '复兴中路579号',
          notas: 'Cócteles de estilo japonés. Cada planta del bar tiene su ambiente; la tercera es la más cuidada.',
          gastos: [{ concepto: 'dos cócteles (75–150 ¥ cada uno)', min: 160, max: 260 }],
          enlaces: [enlace('Speak Low', 'https://rachelgouk.com/listings/speak-low/')],
        },
        {
          hora: '23:45',
          fin: '26:00',
          nombre: 'Hush (INS Land)',
          local: 'INS新乐园',
          categoria: 'ocio',
          ...en(C.hush),
          opcional: true,
          llegada: { modo: 'a_pie' },
          direccion: '109 Yandang Road',
          direccionLocal: '雁荡路109号',
          notas:
            'Si apetece hip-hop/R&B. Comprobar la sesión y el precio de la entrada de esa noche antes de comprar pases: es jueves, así que puede haber menos ambiente que un fin de semana.\n' +
            'Es la víspera de Disneyland: si se quiere entrar al parque a las 8:30, mejor terminar la noche en Speak Low.\n' +
            'Si llegamos cansados, el bar ya cumple el plan nocturno y la discoteca se puede omitir. Hora de salida orientativa.\n' +
            'INS Land está en el lado norte del parque Fuxing; el punto del mapa es aproximado.',
          gastos: [{ concepto: 'entrada (la de fin de semana; la del jueves, por confirmar)', min: 198, max: 288 }],
          enlaces: [enlace('Hush', 'https://www.smartshanghai.com/venue/28730/smshwxmpqr.jpeg?share=true28730')],
        },
        {
          ...HOTEL,
          hora: '26:30',
          llegada: { modo: 'taxi', min: 20 },
        },
      ],
    },
    {
      fecha: '2026-10-23',
      titulo: 'Shanghai Disneyland en Halloween',
      ciudad: 'Shanghái',
      notas:
        'Levantarnos a las 08:00 y dedicarle el día completo. No añadir otro plan obligatorio después.\n' +
        'Comida y cena: huecos flexibles dentro del parque o a la salida, según hambre, colas y hora de cierre.',
      paradas: [
        {
          hora: '09:45',
          fin: '21:40',
          nombre: 'Shanghai Disneyland',
          local: '上海迪士尼乐园',
          categoria: 'ocio',
          ...en(C.disney),
          llegada: { modo: 'metro', detalle: 'Metro hasta Disney Resort (línea 11) o taxi/DiDi', min: 60 },
          notas:
            'Viernes 23: día especial de Halloween («Spook-tacular Day»), todo incluido en la entrada. Parque de 8:30 a 22:00 (calendario oficial). Desfile de Mickey a las 12:15 y 15:45; desfile de Halloween a las 14:15 y 18:15, seguido de la celebración de villanos en el castillo; zonas de fiesta de 18:00 a 22:00; espectáculo nocturno a las 21:15. Confirmarlo en la app la víspera.\n' +
            'Disfraces: se puede ir disfrazado, también los adultos. Nada que llegue por debajo del tobillo, sin máscara ni maquillaje que tape toda la cara, nada puntiagudo ni que parezca un arma y accesorios de 50 cm como máximo; no se puede cambiar en los aseos.\n' +
            'Entrada del 23: 629 ¥ por adulto (Early Bird, 579 ¥, comprándola antes del 13 de octubre, sin reembolso ni cambios; la normal se reembolsa gratis hasta el 16). Paquete de Halloween, 1.288 ¥: entrada, Premier Access de Piratas, sitio reservado para el desfile de las 18:15 y para el espectáculo nocturno, y bebida con corona. En la web o la app oficial, o en Trip.com (socio oficial), con los datos del pasaporte: se entra pasándolo por el torno.\n' +
            'Premier Access (saltarse la cola): 180 ¥ por atracción grande y 140 ¥ las pequeñas, solo el mismo día, en la app y ya dentro del parque; Zootopia y TRON se agotan pronto. Early Park Entry (1 h antes): 199 ¥ en viernes. No hay fila virtual gratis.\n' +
            'Si se puede, entrar a la apertura: Zootopia, Seven Dwarfs y Peter Pan a primera hora; fila single rider en TRON, Seven Dwarfs y Roaring Rapids. Explorer Canoes, cerrada por reforma. Por la tarde, Halloween: desfile de las 18:15, villanos en el castillo y zonas de fiesta hasta el espectáculo de las 21:15.\n' +
            'El punto del mapa es el centro del parque, no la puerta de entrada.',
          gastos: [
            { concepto: 'entrada del 23 (Early Bird: 579 ¥)', min: 629 },
            { concepto: 'Premier Access de Zootopia (opcional)', min: 0, max: 180 },
            { concepto: 'comida y cena de servicio rápido', min: 120, max: 240 },
            { concepto: 'snacks (pata de pavo 85 ¥, polo de Zootopia 45 ¥)', min: 20, max: 130 },
          ],
          subparadas: [
            {
              nombre: 'TRON Lightcycle Power Run',
              local: '创极速光轮',
              ...en(D.tron),
              notas: 'La montaña rusa más rápida del parque, en moto y con lanzamiento (122 cm). Unos 50 min de cola: fila single rider o Premier Access (180 ¥). De noche luce más.',
            },
            {
              nombre: 'Seven Dwarfs Mine Train',
              local: '七个小矮人矿山车',
              ...en(D.sieteEnanitos),
              notas: 'Montaña rusa familiar con vagones que se balancean (97 cm). Unos 70 min de cola: a primera hora o por la fila single rider. En Halloween, la Reina Malvada ronda por aquí.',
            },
            {
              nombre: 'Castillo y «Once Upon a Time» Adventure',
              local: '奇幻童话城堡 · 漫游童话时光',
              ...en(D.castillo),
              notas: 'El castillo Disney más grande del mundo y la foto del día; dentro, un recorrido a pie de Blancanieves (unos 10 min de cola). En Halloween salen villanos al balcón de 8:30 a 17:45, con paseo de villanos a las 12:00.',
            },
            {
              nombre: 'Zootopia: Hot Pursuit',
              local: '疯狂动物城：热力追踪',
              ...en(D.zootopia),
              notas: 'La única zona Zootopia del mundo y la atracción más popular del parque (suave, 81 cm). Colas de 60–90 min: a primera hora o con Premier Access (180 ¥).',
            },
            {
              nombre: 'Desfile Mickey’s Storybook Express',
              local: '米奇童话专列',
              ...en(D.desfile),
              notas: 'A las 12:15 y 15:45 (unos 14 min, con el pre-desfile de Duffy y la carroza de Zootopia). Delante del castillo se llena: más hueco en Tomorrowland y Toy Story Land, 15–20 min antes.',
            },
            {
              nombre: 'Pirates of the Caribbean: Battle for the Sunken Treasure',
              local: '加勒比海盗——沉落宝藏之战',
              ...en(D.piratas),
              notas: 'Versión exclusiva de Shanghái, con una batalla submarina: para muchos, el mejor dark ride de Disney. Unos 25 min de cola: buena para mediodía.',
            },
            {
              nombre: 'Roaring Rapids',
              local: '雷鸣山漂流',
              ...en(D.rapidos),
              notas: 'Rápidos con un monstruo animatrónico gigante; te mojas bastante (107 cm). Mejor a primera hora de la tarde; single rider o Premier Access (180 ¥).',
            },
            {
              nombre: 'Soaring Over the Horizon',
              local: '翱翔•飞越地平线',
              ...en(D.soaring),
              notas: 'Vuelo simulado sobre maravillas del mundo, suave (102 cm). La cola más larga del parque (unos 80 min): Premier Access (180 ¥) o la última hora.',
            },
            {
              nombre: 'Desfile de Halloween de Donald',
              local: '唐老鸭和朋友们的反派巡游',
              ...en(D.desfile),
              notas: 'A las 14:15 y 18:15: los villanos de protagonistas, Mickey y compañía en versión steampunk y Pete; eligen a gente disfrazada para desfilar. El de las 18:15 enlaza con la celebración de villanos en el castillo.',
            },
            {
              nombre: 'Celebración de villanos en el castillo',
              local: '迪士尼反派魅影秀',
              ...en(D.desfile),
              notas: 'Solo en los días especiales de Halloween: proyecciones con los villanos sobre el castillo, después del desfile de las 18:15 (hacia las 18:45, sin confirmar). Se ve desde los jardines de delante del castillo.',
            },
            {
              nombre: 'Zonas de fiesta de Halloween',
              local: '怪好玩蹦迪舞池',
              ...en(D.fiestaTomorrowland),
              notas: 'Cinco pistas con DJ, bailarines y personajes, de 18:00 a 22:00 (horario de 2025): Tomorrowland (este punto), Treasure Cove, Adventure Isle, Fantasyland y Zootopia. Solo en los días especiales.',
            },
            {
              nombre: 'ILLUMINATE! y el final del 10.º aniversario',
              local: '奇梦之光幻影秀',
              ...en(D.illuminate),
              notas: 'A las 21:15: proyecciones, fuegos y láser sobre el castillo. Coger sitio en el eje central, junto a la estatua Storytellers, 30–40 min antes (zona reservada: 299 ¥).',
            },
            {
              nombre: 'Peter Pan’s Flight',
              local: '小飞侠天空奇遇',
              opcional: true,
              ...en(D.peterPan),
              notas: 'Más larga y moderna que la de París. Unos 30 min de cola; Premier Access, 140 ¥.',
            },
            {
              nombre: 'Villains’ Club',
              local: '反派俱乐部',
              opcional: true,
              ...en(D.fiestaTomorrowland),
              notas: 'Espectáculo de villanos de Halloween en el escenario de Tomorrowland, a las 19:00 y 19:50 (horario de estos días).',
            },
            {
              nombre: 'Buccaneer Bash',
              opcional: true,
              ...en(D.fiestaTesoro),
              notas: 'Fiesta pirata de Halloween en Treasure Cove, de 17:50 a 20:20 (horario de estos días).',
            },
            {
              nombre: 'Fiesta de Donald (Treat Party)',
              local: '唐老鸭捣蛋派对',
              opcional: true,
              ...en(D.bosqueFestival),
              notas: 'En Festival Forest (Fantasyland), de día: en 2025 a las 10:30, 11:30, 13:30 y 14:30.',
            },
            {
              nombre: 'Truco o trato',
              local: '不给糖就捣蛋',
              opcional: true,
              ...en(D.evergreen),
              notas: 'De 18:30 a 21:30 (horario de 2025) en Evergreen Playhouse (este punto), Story House Stage y el Teatro Fandango.',
            },
            {
              nombre: 'Personajes de Halloween',
              opcional: true,
              ...en(D.meetingPost),
              notas: 'Lotso en Meeting Post (este punto), Chip y Dale en Trading Post, Jack y Sally en Fantasyland, Pete en Mickey Avenue, la Reina Malvada en Seven Dwarfs y Loki en Marvel Universe.',
            },
            {
              nombre: 'The Heart of Magic',
              local: '奇妙之心城堡秀',
              opcional: true,
              ...en(D.corazon),
              notas: 'Espectáculo nuevo del 10.º aniversario frente al castillo (debutan Hércules y Miguel, de Coco): estos días a las 10:05, 11:30, 13:40 y 15:05 (el horario del 23, aún sin publicar).',
            },
            {
              nombre: 'Mickey’s Storybook Adventure',
              local: '华特迪士尼大剧院',
              opcional: true,
              ...en(D.teatro),
              notas: 'Musical de calidad Broadway de 28 min en el Walt Disney Grand Theatre; para varias guías, el mejor espectáculo del parque. De 5 a 8 pases al día.',
            },
            {
              nombre: 'Eye of the Storm: Captain Jack’s Stunt Spectacular',
              opcional: true,
              ...en(D.tormenta),
              notas: 'Espectáculo de especialistas de 30 min a cubierto: buen descanso. Muchos pases al día.',
            },
            {
              nombre: 'Rex’s Racer',
              local: '抱抱龙冲天赛车',
              opcional: true,
              ...en(D.rex),
              notas: 'Montaña rusa en U que va y viene, intensa y corta (120 cm). Unos 50 min de cola.',
            },
            {
              nombre: 'Jet Packs',
              local: '喷气背包飞行器',
              opcional: true,
              ...en(D.jetPacks),
              notas: 'Giratoria en la que se vuela tumbado boca abajo (112 cm). Unos 35 min de cola.',
            },
            {
              nombre: 'Challenge Trails',
              local: '古迹探索营 · 绳索挑战道',
              opcional: true,
              ...en(D.cuerdas),
              notas: 'Circuito de cuerdas con arnés por las paredes de la montaña, exclusivo de Shanghái (106 cm). Solo de día.',
            },
            {
              nombre: 'Zootopia en Halloween y Judy & Nick',
              local: '疯狂动物城 嚎叫节',
              opcional: true,
              ...en(D.zootopiaCentro),
              notas: 'Aullidos de Halloween a las 17:10, 18:10 y 19:10, y la bebida azul de temporada en Jumbeaux’s Café. Judy y Nick: de 30 a 60 min de cola.',
            },
            {
              nombre: 'LinaBell',
              local: '萌友小站 · 玲娜贝儿',
              opcional: true,
              ...en(D.linaBell),
              notas: 'El personaje fenómeno en China, con la cola más larga del parque (horas): vale la pena ver el ambiente. Posición aproximada.',
            },
            {
              nombre: 'Duffy y sus amigos',
              local: '达菲和朋友们',
              opcional: true,
              ...en(D.duffy),
              notas: 'Encuentros cortos en las tiendas de Mickey Avenue; las horas salen en la app del día.',
            },
            {
              nombre: 'Marvel Universe',
              local: '漫威英雄总部',
              opcional: true,
              ...en(D.marvel),
              notas: 'Pabellón con Capitán América, Spider-Man y la experiencia de Iron Man; en Halloween, también Loki. De 5 a 10 min de cola.',
            },
            {
              nombre: 'Pixar Adventurous Journey',
              opcional: true,
              ...en(D.pixar),
              notas: 'Exposición inmersiva de siete mundos Pixar (2025), rápida y muy fotogénica. Posición aproximada.',
            },
            {
              nombre: 'Laberinto de Alicia',
              local: '爱丽丝梦游仙境迷宫',
              opcional: true,
              ...en(D.alicia),
              notas: 'Laberinto fotogénico con la Reina Roja y la merienda del Sombrerero, sin cola; en los días especiales de Halloween, con naipes y el Sombrerero de día.',
            },
            {
              nombre: 'Jardín de los Doce Amigos',
              local: '十二朋友园',
              opcional: true,
              ...en(D.doceAmigos),
              notas: 'Mosaicos del zodiaco chino con personajes Disney, exclusivo de Shanghái: buscad vuestro signo.',
            },
            {
              nombre: 'Pata de pavo (Tortuga Treats)',
              local: '土图嘉风味',
              opcional: true,
              ...en(D.tortuga),
              notas: 'El snack más famoso del parque, unos 85 ¥ (puede que se venda a partir de las 14:30).',
            },
            {
              nombre: 'Pawpsicle (Jumbeaux’s Café)',
              local: '大象甜品店',
              opcional: true,
              ...en(D.jumbeaux),
              notas: 'El polo con forma de pata de la película, de espino y gofre (unos 45 ¥); en Halloween, también la bebida azul de curaçao.',
            },
            {
              nombre: 'Churros de sésamo negro (Stargazer Grill)',
              opcional: true,
              ...en(D.stargazer),
              notas: 'Churros de Halloween, solo en temporada.',
            },
            {
              nombre: 'Hot dog de calabaza (Timothy’s Treats)',
              opcional: true,
              ...en(D.timothy),
              notas: 'Hot dog con salsa de calabaza, solo en temporada.',
            },
            {
              nombre: 'CookieAnn Bakery Café',
              local: '琦妙美味屋',
              opcional: true,
              ...en(D.cookieAnn),
              notas: 'La pastelería de Duffy y sus amigos: dulces con forma de personaje.',
            },
            {
              nombre: 'Wandering Moon Teahouse',
              local: '漫月食府',
              opcional: true,
              ...en(D.lunaErrante),
              notas: 'Servicio rápido con cocinas de varias regiones de China en un pabellón de jardín: buena para comer.',
            },
            {
              nombre: 'Avenue M Arcade',
              local: 'M大街购物廊',
              opcional: true,
              ...en(D.avenidaM),
              notas: 'La tienda más grande del parque (10.º aniversario, las cuatro colecciones de Halloween, Duffy y LinaBell): mejor al final, junto a la salida.',
            },
            {
              nombre: 'Disneytown y World of Disney',
              local: '迪士尼小镇',
              opcional: true,
              ...en(C.disneytown),
              notas: 'Fuera del parque, de camino al metro: comer sale más barato y está la enorme World of Disney Store, abierta después del cierre.',
            },
            {
              nombre: 'Wishing Star Park',
              local: '星愿公园',
              opcional: true,
              ...en(D.estrellaDeseos),
              notas: 'Paseo gratis por el lago con el castillo a lo lejos: solo encaja antes de entrar.',
            },
          ],
          enlaces: [
            enlace('Entradas (web oficial)', 'https://www.shanghaidisneyresort.com/en/commerce/ticketing-v2/tickets/shdr-theme-park-tickets/ThemePark/booth'),
            enlace('Calendario del parque', 'https://www.shanghaidisneyresort.com/en/park-calendar'),
            enlace('Halloween 2026 (nota oficial)', 'https://shcorporate.shanghaidisneyresort.com/en/step-into-a-golden-autumn-with-duffy-month-halloween-and-seasonal-discoveries-at-shanghai-disney-resort.html'),
            enlace('Normas de disfraces', 'https://www.shanghaidisneyresort.com/en/announcement/halloween-guest-costume-guideline'),
            enlace('Premier Access: condiciones', 'https://www.shanghaidisneyresort.com/en/legal/disney-premier-access-terms-conditions'),
          ],
        },
        {
          ...HOTEL,
          hora: '22:50',
          llegada: { modo: 'metro', detalle: 'Metro (línea 11 y transbordo) o taxi/DiDi', min: 70 },
          notas: 'Después de Disney, cerca del hotel quedan pocas cosas abiertas: lo de abajo es lo que se ha podido confirmar.',
          subparadas: [
            {
              nombre: 'Paseo por el río y el puente Baihe',
              local: '苏州河百合桥',
              opcional: true,
              ...en(C.baihe),
              direccionLocal: '恒丰路苏州河百合桥（苏河1号旁）',
              notas: 'A dos minutos: el puente peatonal nuevo y el paseo del río. A esa hora ya sin las luces decorativas (se apagan a las 21:30): paseo tranquilo más que foto.',
            },
            {
              nombre: 'Lawson',
              local: '罗森便利店',
              opcional: true,
              ...en(C.lawson),
              direccionLocal: '恒丰路688号（苏河1号）旁 罗森',
              notas: 'Junto al hotel: agua, cerveza, fruta y oden (关东煮) caliente. Horario sin confirmar; hay un FamilyMart (全家) a 160 m.',
            },
            {
              nombre: 'McDonald’s 24 h (Changshou Road)',
              local: '麦当劳（长寿路店）',
              opcional: true,
              ...en(C.mcdonaldsChangshou),
              direccionLocal: '上海市普陀区长寿路393号',
              notas: 'Plan B si se llega con hambre y está todo cerrado: abre las 24 horas (lista oficial de 2026). A 2 km, 5–8 min en taxi.',
            },
          ],
        },
      ],
    },
    {
      fecha: '2026-10-24',
      titulo: 'Nankín: Museo Paleontológico',
      ciudad: 'Nankín',
      notas:
        'La excursión es para el Museo Paleontológico, no para encadenar monumentos. Levantarnos a las 10:00.\n' +
        'Es sábado: trenes y museo con más gente que entre semana.\n' +
        'Billetes: comprobar ya la app oficial 12306. La venta suele abrir 15 días antes (para el 24, hacia el 9 de octubre), pero en 2026 hay solicitud anticipada para algunos trenes del corredor Pekín–Shanghái. Solicitar plaza no es tenerla confirmada.\n' +
        'Fuera del plan: Niushoushan, Mausoleo Ming Xiaoling, Palacio Presidencial y los demás museos.',
      paradas: [
        {
          hora: '10:45',
          fin: '11:10',
          nombre: 'Estación de Shanghái',
          local: '上海站',
          categoria: 'transporte',
          ...en(C.estacionShanghai),
          llegada: { modo: 'a_pie', detalle: 'Unos 600 m por Hengfeng Rd y Moling Rd hasta la plaza sur', min: 10 },
          notas:
            'Tren hacia la estación de Nankín sobre las 11:00–11:30, si hay un horario que deje tiempo suficiente. Tren y duración exactos pendientes de reserva. Llevar el pasaporte.',
          gastos: [{ concepto: 'tren de ida, 2.ª clase', min: 110, max: 160 }],
          enlaces: [
            enlace('Información ferroviaria', 'https://english.beijing.gov.cn/travellinginbeijing/transportation/railway/202607/t20260720_4772390.html'),
          ],
        },
        {
          hora: '12:50',
          nombre: 'Estación de Nankín',
          local: '南京站',
          categoria: 'transporte',
          ...en(C.estacionNankin),
          llegada: { modo: 'tren', detalle: 'Tren G/D (horario pendiente de reserva)', min: 100 },
        },
        {
          hora: '13:15',
          fin: '13:50',
          nombre: 'Comida junto a Jiming Temple',
          corto: 'la comida',
          categoria: 'comida',
          ...en(C.comidaJiming),
          llegada: { modo: 'metro', detalle: 'Línea 3 hasta Jiming Temple (鸡鸣寺)', min: 15 },
          notas:
            'Comida sencilla por la zona, por ejemplo fideos locales con pato. El museo está a unos 200 m de la salida 5 del metro.\n' +
            'En días de mucha gente la salida 5 es solo de entrada; para salir se usa la 6 (o la 1 y la 4).\n' +
            'Otras especialidades baratas de Nankín: sopa de fideos con sangre de pato (鸭血粉丝汤, ~15 ¥) y fideos con piel de cerdo (皮肚面, ~25 ¥).',
          gastos: [{ concepto: 'comida', min: 20, max: 50 }],
        },
        {
          hora: '14:00',
          fin: '16:30',
          nombre: 'Museo Paleontológico de Nankín',
          corto: 'el museo',
          local: '南京古生物博物馆',
          categoria: 'museo',
          ...en(C.museo),
          llegada: { modo: 'a_pie' },
          direccion: '39 Beijing East Road',
          direccionLocal: '北京东路39号',
          notas:
            'Gratuito. Abre de miércoles a domingo de 09:00 a 17:00, último acceso a las 16:00 (lunes y martes cerrado).\n' +
            'Cada adulto necesita reserva nominal y su propio código en el WeChat oficial del museo; en sábado las plazas se acaban antes, así que conviene reservar en cuanto se abran.',
          gastos: [{ concepto: 'entrada', min: 0 }],
          enlaces: [enlace('Guía oficial del museo', 'https://www.nmp.ac.cn/bwggk/cgzn/')],
        },
        {
          hora: '16:40',
          fin: '17:10',
          nombre: 'Paseo junto a Jiming Temple',
          corto: 'el paseo',
          local: '鸡鸣寺',
          categoria: 'cultura',
          ...en(C.jiming),
          opcional: true,
          llegada: { modo: 'a_pie' },
          notas: 'Breve, solo si apetece. El templo abre de 07:00 a 17:30.',
          gastos: [{ concepto: 'entrada (aprox., sin confirmar)', min: 10 }],
        },
        {
          hora: '17:35',
          fin: '18:00',
          nombre: 'Estación de Nankín',
          local: '南京站',
          categoria: 'transporte',
          ...en(C.estacionNankin),
          llegada: { modo: 'metro', detalle: 'Línea 3', min: 20 },
          notas: 'Tren de regreso a Shanghái (horario pendiente de reserva).',
          gastos: [{ concepto: 'tren de vuelta, 2.ª clase', min: 110, max: 160 }],
        },
        {
          hora: '19:40',
          nombre: 'Estación de Shanghái',
          local: '上海站',
          categoria: 'transporte',
          ...en(C.estacionShanghai),
          llegada: { modo: 'tren', detalle: 'Tren G/D de vuelta', min: 100 },
        },
        {
          ...HOTEL,
          hora: '20:00',
          llegada: { modo: 'a_pie', min: 10 },
          notas: 'Cena sencilla cerca del hotel.',
          gastos: [{ concepto: 'cena sencilla', min: 40, max: 80 }],
        },
      ],
    },
    {
      fecha: '2026-10-25',
      titulo: 'Historia Natural, Wukang/Anfu, cafés y vistas',
      ciudad: 'Shanghái',
      notas:
        'Después de Nankín, levantarnos sobre las 11:00.\n' +
        'Con el museo, los cafés pasan a la tarde y Lujiazui se ve ya de noche.',
      paradas: [
        {
          hora: '11:45',
          fin: '14:00',
          nombre: 'Museo de Historia Natural de Shanghái',
          corto: 'el museo',
          local: '上海自然博物馆',
          categoria: 'museo',
          ...en(C.museoHistoriaNatural),
          llegada: { modo: 'taxi', detalle: 'Taxi (10 min) o andando (~1,5 km)', min: 10 },
          direccion: '510 West Beijing Road, en el parque de esculturas de Jing’an',
          direccionLocal: '北京西路510号',
          notas:
            'Hay que reservar con antelación: no venden entradas en taquilla.\n' +
            'Abre de martes a domingo de 09:00 a 17:15, con última entrada sobre las 16:00; los lunes cierra. Se recomiendan 2–3 h.\n' +
            'En fin de semana suele haber muchas familias.',
          gastos: [{ concepto: 'entrada', min: 30 }],
          enlaces: [
            enlace('Museo (Time Out)', 'https://www.timeoutshanghai.com/venue/Things_to_Do-Museums/1309/Shanghai-Natural-History-Museum.html'),
          ],
        },
        {
          hora: '14:20',
          fin: '15:20',
          nombre: 'Comida en el n.º 98 de Wukang Road',
          corto: 'la comida',
          categoria: 'comida',
          ...en(C.dongxin),
          llegada: { modo: 'taxi', min: 15 },
          direccion: '98 Wukang Road',
          direccionLocal: '武康路98号',
          notas:
            'Dos restaurantes en el mismo número. Posición en el mapa aproximada.',
          subparadas: [
            {
              nombre: 'SOMETHING Dining & Bar',
              notas: '2.ª planta. Brunch y cocina occidental de 10:00 a 22:00: a esta hora, lo seguro.',
            },
            {
              nombre: 'Dongxin Jiujia',
              opcional: true,
              notas: 'Cocina shanghainesa. Sin confirmar si sirve después de las 14:00.',
            },
          ],
          gastos: [{ concepto: 'comida (estimado, sin precio publicado)', min: 100, max: 180 }],
          enlaces: [
            enlace('SOMETHING', 'https://english.shanghai.gov.cn/en-Restaurants/20240416/b3de189a44064a76afd2e677f7e60b37.html'),
            enlace('Restaurantes de Wukang', 'https://english.shanghai.gov.cn/en-Restaurants/20250411/1dfa64b624304bff969afd23b9d2bb24.html'),
          ],
        },
        {
          hora: '15:25',
          fin: '15:50',
          nombre: 'Wukang Road y Wukang Mansion',
          corto: 'Wukang Road',
          local: '武康大楼 · 武康路',
          categoria: 'barrio',
          ...en(C.wukang),
          llegada: { modo: 'a_pie' },
          notas: 'Paseo y compras relajadas por Wukang Road y Anfu Road: boutiques y diseño local, sin obligación de comprar.',
        },
        {
          hora: '16:05',
          fin: '16:50',
          nombre: '13DEMARZO Café',
          categoria: 'comida',
          ...en(C.demarzo),
          llegada: { modo: 'a_pie' },
          direccion: '322 Anfu Road',
          direccionLocal: '安福路322号',
          notas:
            'La bebida con el osito. Abre de 10:00 a 21:30. Puede haber cola, sobre todo en domingo: pedir primero y seguir mirando tiendas por Anfu mientras esperamos, si el sistema de recogida lo permite.',
          gastos: [{ concepto: 'bebida (la más pedida, el latte de rosa, cuesta 36 ¥)', min: 30, max: 40 }],
          enlaces: [
            enlace(
              'Ubicación y horarios',
              'https://maps.apple.com/place?address=Anfu+Road+No.322+Building+4+Building+1%2C+Xuhui%2C+Shanghai+China&auid=1118692146049105&coordinate=31.213256%2C121.440149&lsp=57879&name=13+DE+MARZO+Caf+%28Shanghai+Anfu+Road+Branch%29',
            ),
          ],
        },
        {
          hora: '17:05',
          fin: '17:35',
          nombre: 'CUBIC3: -86°C Dirty',
          categoria: 'comida',
          ...en(C.cubic3),
          llegada: { modo: 'taxi', min: 12 },
          direccion: '58 Yongkang Road',
          direccionLocal: '永康路58号',
          notas:
            'El «−86 °C» se refiere a la experiencia del vaso, no a beber líquido a esa temperatura.\n' +
            'Tramo flexible si la espera en 13DEMARZO se alarga. Posición en el mapa aproximada (Yongkang Road).',
          gastos: [{ concepto: 'bebida (estimado, sin precio publicado)', min: 40, max: 70 }],
          enlaces: [enlace('CUBIC3 en Amap', 'https://www.amap.com/place/B0LUF51YXH')],
        },
        {
          hora: '17:35',
          fin: '18:00',
          nombre: 'Hinichijou (Bear Paw Café)',
          categoria: 'comida',
          ...en(C.hinichijou),
          llegada: { modo: 'a_pie' },
          notas:
            'El café servido por una «garra» a través de un hueco en la pared; lo atienden baristas sordos. Se pide escaneando un código QR.\n' +
            'Comprobar el horario: los cafés de la zona suelen cerrar a media tarde. Muy cerca de CUBIC3; posición en el mapa aproximada.',
          gastos: [{ concepto: 'café (todos cuestan unos 20 ¥)', min: 20, max: 35 }],
          enlaces: [enlace('Hinichijou', 'https://english.shanghai.gov.cn/en-Cafes/20240823/f098caef928a48a495162811624512a4.html')],
        },
        {
          hora: '18:40',
          fin: '19:20',
          nombre: 'Lujiazui de noche',
          local: '陆家嘴环形天桥',
          categoria: 'mirador',
          ...en(C.lujiazui),
          llegada: { modo: 'metro', detalle: 'Metro hasta Lujiazui (línea 2) o taxi', min: 35 },
          notas: 'Pasarela circular entre los rascacielos, ya iluminados.',
        },
        {
          hora: '19:25',
          fin: '21:00',
          nombre: 'Torre Perla Oriental',
          corto: 'la Torre Perla',
          local: '东方明珠',
          categoria: 'mirador',
          ...en(C.perla),
          llegada: { modo: 'a_pie' },
          notas:
            'Cena pendiente de decidir: restaurante giratorio (bufé de cena, entrada a la torre incluida) si valoramos la experiencia y aceptamos su precio, o solo el mirador y cena aparte por la zona (sumar ~80–150 ¥).\n' +
            'No considerar la cena giratoria reservada.',
          gastos: [{ concepto: 'mirador (199–220 ¥) o bufé giratorio de cena (~418 ¥)', min: 199, max: 418 }],
          enlaces: [enlace('Precios de la torre', 'https://wanderinchina.com/destinations/shanghai/oriental-pearl-tower/')],
        },
        {
          ...HOTEL,
          hora: '21:40',
          llegada: { modo: 'metro', detalle: 'Línea 2 y transbordo, o taxi', min: 35 },
          notas: 'Ordenar compras y pesar la maleta.',
        },
      ],
    },
    {
      fecha: '2026-10-26',
      titulo: 'Regreso',
      ciudad: 'Shanghái',
      notas: 'Salir del hotel a las 07:45–08:00. No dejar compras ni visitas para esta mañana.',
      paradas: [
        {
          ...HOTEL,
          hora: '07:15',
          fin: '07:50',
          notas: 'Check-out.',
        },
        {
          ...PVG,
          hora: '09:05',
          fin: '12:40',
          llegada: { modo: 'taxi', detalle: 'Taxi o DiDi (según tráfico)', min: 75 },
          notas: 'Vuelo a las 12:40 hacia Ámsterdam; llegada a Barcelona a las 23:05. Martes 27: Barcelona 06:50 → Málaga 08:35.',
        },
      ],
    },
  ],
  secciones: [
    {
      titulo: 'Lo que queremos priorizar',
      puntos: [
        'Disfrutar Shanghái sin madrugar: levantarnos a las 10:00 como muy pronto. Excepciones: Disneyland (08:00) y el vuelo de vuelta.',
        'Comprar una maleta y ropa allí; descubrir marcas chinas originales con buena relación calidad-precio.',
        'Probar comidas y bebidas curiosas.',
        'Disneyland, el Museo Paleontológico de Nankín y una noche de buenos cócteles y baile.',
        'No meter todos los sitios de la lista por obligación.',
      ],
    },
    {
      titulo: 'Vuelos',
      puntos: [
        'Ida: lunes 19, Málaga 23:05 → Barcelona 00:40 (martes 20).',
        'Martes 20: Barcelona 06:10 → París → Shanghái-Pudong, llegada el miércoles 21 a las 07:00.',
        'Vuelta: lunes 26, Pudong 12:40 → Ámsterdam → Barcelona 23:05.',
        'Martes 27: Barcelona 06:50 → Málaga 08:35.',
      ],
    },
    {
      titulo: 'Hotel',
      puntos: [
        'Aqua Suhe NO.1 Hotel (Shanghai Jing’an), 688 Hengfeng Road. Cinco noches, del 21 al 26.',
        'Entrada después de las 14:00; salida antes de las 12:00.',
        'Desayuno incluido del 22 al 26, de 07:00 a 10:00: preguntar si lo dan para llevar, sin contar con ello.',
      ],
      enlaces: [enlace('Ficha del hotel', 'https://sg.trip.com/hotels/jing-an-district-hotel-detail-2895314/aqua-suhe-no-1-hotel-shanghai-jingan/')],
    },
    {
      titulo: 'Fuera del plan por ahora',
      puntos: [
        'Nankín: Niushoushan, Mausoleo Ming Xiaoling, Palacio Presidencial y los demás museos.',
        'Shanghái: Museo de Arte Contemporáneo, China Art Museum, Templo del Buda de Jade y varios centros comerciales.',
        'Masaje en Kangyou Four Seasons (222 Jinyuan Road): era el plan para el miércoles si no había habitación temprano.',
      ],
    },
  ],
  pendientes: [
    'Museo de Historia Natural (domingo 25): reservar la entrada (no venden en taquilla).',
    'Miércoles 21: confirmar la última entrada de la noria Sky Ring y hasta qué hora sirve Top Banana Market.',
    'Tren y museo: comprobar 12306, elegir estaciones y horarios reales y hacer la reserva nominal del museo.',
    'Disneyland (viernes 23, día de Halloween): comprar la entrada y consultar el horario del día.',
    'Equipaje: verificar la franquicia de los cuatro vuelos antes de comprar la maleta.',
    'Domingo noche: decidir cena giratoria en la Perla o solo vistas; reservar solo tras ver el precio final.',
    'Jueves noche: mirar la programación y la entrada de Hush/INS para el 22.',
  ],
};
