import type { Itinerario } from '../tipos';

// ITINERARIO DE EJEMPLO: se sustituirá por el real.
//
// Cada parada: hora de llegada, nombre (y en chino), categoría, coordenadas y cómo se llega
// desde la parada anterior. Si no se pone `fin`, la hora de salida se calcula con la duración
// del trayecto hasta la siguiente parada.

export const itinerario: Itinerario = {
  titulo: 'Shanghái y Nankín',
  ejemplo: true,
  dias: [
    {
      fecha: '2026-10-10',
      titulo: 'Llegada y el Bund',
      ciudad: 'Shanghái',
      paradas: [
        {
          hora: '14:30',
          fin: '15:15',
          nombre: 'Aeropuerto de Pudong',
          local: '浦东国际机场',
          categoria: 'transporte',
          lat: 31.1427359,
          lng: 121.8041131,
          notas: 'Llegada. Sacar efectivo y comprobar que Alipay funciona.',
        },
        {
          hora: '16:30',
          nombre: 'Hotel (ejemplo)',
          local: '人民广场',
          categoria: 'hotel',
          lat: 31.2349,
          lng: 121.4727,
          llegada: { modo: 'maglev', detalle: 'Maglev hasta Longyang Rd + metro línea 2', min: 75 },
          reserva: 'Código de reserva de ejemplo',
        },
        {
          hora: '17:30',
          nombre: 'Calle Nanjing Este',
          local: '南京东路步行街',
          categoria: 'barrio',
          lat: 31.2376841,
          lng: 121.4753016,
          llegada: { modo: 'a_pie' },
        },
        {
          hora: '18:45',
          fin: '21:00',
          nombre: 'El Bund',
          local: '外滩',
          categoria: 'mirador',
          lat: 31.2353356,
          lng: 121.487632,
          llegada: { modo: 'a_pie' },
          notas: 'Skyline de Pudong iluminado hasta las 22:00.',
        },
        {
          hora: '21:30',
          nombre: 'Hotel (ejemplo)',
          local: '人民广场',
          categoria: 'hotel',
          lat: 31.2349,
          lng: 121.4727,
          llegada: { modo: 'taxi' },
        },
      ],
    },
    {
      fecha: '2026-10-11',
      titulo: 'Ciudad antigua y Pudong',
      ciudad: 'Shanghái',
      paradas: [
        {
          hora: '09:00',
          fin: '11:00',
          nombre: 'Jardín Yuyuan',
          local: '豫园',
          categoria: 'cultura',
          lat: 31.2289274,
          lng: 121.4879752,
          llegada: { modo: 'metro', detalle: 'Línea 10 → Yuyuan Garden', min: 20 },
          notas: 'Ir a primera hora para evitar colas.',
        },
        {
          hora: '11:30',
          nombre: 'Xintiandi',
          local: '新天地',
          categoria: 'comida',
          lat: 31.2219311,
          lng: 121.4704371,
          llegada: { modo: 'taxi', min: 15 },
          notas: 'Comida.',
        },
        {
          hora: '13:30',
          fin: '15:00',
          nombre: 'Tianzifang',
          local: '田子坊',
          categoria: 'barrio',
          lat: 31.21034,
          lng: 121.4641036,
          llegada: { modo: 'a_pie' },
        },
        {
          hora: '15:25',
          nombre: 'Embarcadero Jinling Rd',
          local: '金陵东路渡口',
          categoria: 'transporte',
          lat: 31.2346608,
          lng: 121.4889614,
          llegada: { modo: 'taxi', min: 20 },
        },
        {
          hora: '15:45',
          nombre: 'Embarcadero Dongchang Rd',
          local: '东昌路渡口',
          categoria: 'transporte',
          lat: 31.2321352,
          lng: 121.500438,
          llegada: { modo: 'ferry', detalle: 'Ferry por el río Huangpu (2 ¥)', min: 10 },
        },
        {
          hora: '16:15',
          fin: '18:00',
          nombre: 'Shanghai Tower',
          local: '上海中心大厦',
          categoria: 'mirador',
          lat: 31.2356449,
          lng: 121.5012495,
          llegada: { modo: 'a_pie' },
          notas: 'Mirador de la planta 118. Comprar la entrada online.',
        },
        {
          hora: '18:20',
          nombre: 'Perla Oriental',
          local: '东方明珠',
          categoria: 'mirador',
          lat: 31.2419464,
          lng: 121.4952604,
          llegada: { modo: 'a_pie' },
        },
        {
          hora: '20:00',
          nombre: 'Hotel (ejemplo)',
          local: '人民广场',
          categoria: 'hotel',
          lat: 31.2349,
          lng: 121.4727,
          llegada: { modo: 'metro', detalle: 'Línea 2 → People’s Square', min: 20 },
        },
      ],
    },
    {
      fecha: '2026-10-12',
      titulo: 'Excursión a Nankín',
      ciudad: 'Nankín',
      paradas: [
        {
          hora: '07:30',
          fin: '08:05',
          nombre: 'Estación Hongqiao',
          local: '上海虹桥站',
          categoria: 'transporte',
          lat: 31.196127,
          lng: 121.3161092,
          llegada: { modo: 'metro', detalle: 'Línea 2 → Hongqiao Railway Station', min: 45 },
          notas: 'Tren de alta velocidad a las 08:05. Llevar el pasaporte.',
        },
        {
          hora: '09:35',
          nombre: 'Estación Nankín Sur',
          local: '南京南站',
          categoria: 'transporte',
          lat: 31.9712115,
          lng: 118.7927797,
          llegada: { modo: 'tren', detalle: 'Tren G (alta velocidad)', min: 90 },
        },
        {
          hora: '10:30',
          fin: '12:30',
          nombre: 'Mausoleo de Sun Yat-sen',
          local: '中山陵',
          categoria: 'cultura',
          lat: 32.0601798,
          lng: 118.8485432,
          llegada: { modo: 'taxi', min: 35 },
        },
        {
          hora: '13:00',
          fin: '15:30',
          nombre: 'Templo de Confucio',
          local: '夫子庙',
          categoria: 'cultura',
          lat: 32.0262978,
          lng: 118.7857444,
          llegada: { modo: 'taxi', min: 30 },
          notas: 'Comer por la zona: pato salado de Nankín.',
        },
        {
          hora: '16:00',
          fin: '17:10',
          nombre: 'Puerta Zhonghua',
          local: '中华门',
          categoria: 'cultura',
          lat: 32.0145139,
          lng: 118.7762395,
          llegada: { modo: 'a_pie' },
          notas: 'La mayor puerta de la muralla Ming.',
        },
        {
          hora: '17:30',
          fin: '18:00',
          nombre: 'Estación Nankín Sur',
          local: '南京南站',
          categoria: 'transporte',
          lat: 31.9712115,
          lng: 118.7927797,
          llegada: { modo: 'taxi', min: 20 },
        },
        {
          hora: '19:30',
          nombre: 'Estación Hongqiao',
          local: '上海虹桥站',
          categoria: 'transporte',
          lat: 31.196127,
          lng: 121.3161092,
          llegada: { modo: 'tren', detalle: 'Tren G de vuelta', min: 90 },
        },
        {
          hora: '20:30',
          nombre: 'Hotel (ejemplo)',
          local: '人民广场',
          categoria: 'hotel',
          lat: 31.2349,
          lng: 121.4727,
          llegada: { modo: 'metro', detalle: 'Línea 2', min: 45 },
        },
      ],
    },
    {
      fecha: '2026-10-13',
      titulo: 'Jing’an, Concesión Francesa y vuelta',
      ciudad: 'Shanghái',
      paradas: [
        {
          hora: '10:00',
          fin: '11:00',
          nombre: 'Templo Jing’an',
          local: '静安寺',
          categoria: 'cultura',
          lat: 31.225215,
          lng: 121.4407923,
          llegada: { modo: 'metro', detalle: 'Línea 2 → Jing’an Temple', min: 15 },
        },
        {
          hora: '11:15',
          nombre: 'Calle Wukang',
          local: '武康路',
          categoria: 'barrio',
          lat: 31.2138866,
          lng: 121.4361757,
          llegada: { modo: 'taxi', min: 10 },
          notas: 'Pasear por la antigua Concesión Francesa. Comer por la zona.',
        },
        {
          hora: '14:00',
          fin: '15:00',
          nombre: 'Hotel (ejemplo)',
          local: '人民广场',
          categoria: 'hotel',
          lat: 31.2349,
          lng: 121.4727,
          llegada: { modo: 'taxi', min: 20 },
          notas: 'Recoger las maletas.',
        },
        {
          hora: '16:15',
          nombre: 'Aeropuerto de Pudong',
          local: '浦东国际机场',
          categoria: 'transporte',
          lat: 31.1427359,
          lng: 121.8041131,
          llegada: { modo: 'maglev', detalle: 'Metro línea 2 + Maglev', min: 75 },
          notas: 'Vuelo de vuelta.',
        },
      ],
    },
  ],
};
